### ISSUE TITLE
body.split is not a function when use minify: true

### ISSUE THREAD

**Issue by jingsam** [jakubpawlowicz/clean-css#1003]
### Precheck
 
* Do a quick search and make sure a bug has not yet been reported;
* do a quick check if the bug still exists in the latest patch version;
* finally, be nice and have fun!

### Environment

* clean-css version - `npm ls clean-css`: 2.2.23
* node.js version - `node -v`: v6.11.3
* operating system: macOS High Sierra

### Configuration options

This is a `browserify-css` config:

```js
module.exports = {
  autoInject: true,
  autoInjectOptions: {
    verbose: true,
    insertAt: "bottom"
  },
  inlineImages: true,
  inlineImagesOptions: {
    limit: 10000
  },
  minify: true,
  rebaseUrls: false,
  rootDir: './'
};
```

### Input CSS

```css
/* the shorter the better! */
```

### Actual output CSS

When I set `minify: true`, it fails:
```
WARN: Output exceeds 32000 characters
/Users/jingsam/projects/xxx/node_modules/clean-css/lib/properties/optimizer.js:114
    var tokens = body.split(';');
                      ^

TypeError: body.split is not a function
    at tokenize (/Users/jingsam/projects/xxx/node_modules/clean-css/lib/properties/optimizer.js:114:23)
    at Object.process (/Users/jingsam/projects/xxx/node_modules/clean-css/lib/properties/optimizer.js:264:20)
    at optimize (/Users/jingsam/projects/xxx/node_modules/clean-css/lib/selectors/optimizer.js:289:40)
    at Object.process (/Users/jingsam/projects/xxx/node_modules/clean-css/lib/selectors/optimizer.js:337:7)
    at Object.optimizeSelectors (/Users/jingsam/projects/xxx/node_modules/clean-css/lib/clean.js:371:10)
    at replace (/Users/jingsam/projects/xxx/node_modules/clean-css/lib/clean.js:104:19)
    at CleanCSS.minify (/Users/jingsam/projects/xxx/node_modules/clean-css/lib/clean.js:365:5)
    at Object.whenDone (/Users/jingsam/projects/xxx/node_modules/clean-css/lib/clean.js:70:25)
    at processNext (/Users/jingsam/projects/xxx/node_modules/clean-css/lib/imports/inliner.js:96:22)
    at Object.process (/Users/jingsam/projects/xxx/node_modules/clean-css/lib/imports/inliner.js:77:12)
```

### Expected output CSS

```css
```

**Comment by jakubpawlowicz** [comment]
@jingsam any chance of using a newer version of clean-css as 2.2.x is quite old. The code works perfectly well in 3.4.x and 4.x.
