### ISSUE TITLE
Comma-separated css selectors throwing TypeError: Cannot Read property "length" of undefined

### ISSUE THREAD

**Issue by WordsofDefiance** [jakubpawlowicz/clean-css#1076]
Hi,

I'm having some issues with comma-separated selectors. Every comma-separated selector in my SASS file will throw a `Type Error: Cannot Read Property "Length" of undefined` error.

When I change the "format" option to "beautify", it no longer throws the error.

Here's the full error:
```
TypeError: Cannot read property 'length' of undefined
    at Object.rules (/public_html/wp-content/themes/twentyseventeen-child/node_modules/clean-css/lib/writer/helpers.js:48:29)
    at rules (/public_html/wp-content/themes/twentyseventeen-child/node_modules/clean-css/lib/writer/one-time.js:36:11)
    at transformValue (/public_html/wp-content/themes/twentyseventeen-child/node_modules/clean-css/lib/optimizer/level-1/optimize.js:355:18)
    at optimizeBody (/public_html/wp-content/themes/twentyseventeen-child/node_modules/clean-css/lib/optimizer/level-1/optimize.js:473:15)
    at level1Optimize (/public_html/wp-content/themes/twentyseventeen-child/node_modules/clean-css/lib/optimizer/level-1/optimize.js:657:9)
    at optimize (/public_html/wp-content/themes/twentyseventeen-child/node_modules/clean-css/lib/clean.js:144:5)
    at /public_html/wp-content/themes/twentyseventeen-child/node_modules/clean-css/lib/clean.js:120:29
    at /public_html/wp-content/themes/twentyseventeen-child/node_modules/clean-css/lib/reader/read-sources.js:26:64
    at loadOriginalSources (/public_html/wp-content/themes/twentyseventeen-child/node_modules/clean-css/lib/reader/load-original-sources.js:26:5)
    at Object.callback (/public_html/wp-content/themes/twentyseventeen-child/node_modules/clean-css/lib/reader/read-sources.js:26:14)
```

### Environment

* clean-css version - `npm ls clean-css`:
 /public_html/wp-content/themes/twentyseventeen-child
└─┬ gulp-clean-css@3.10.0
  └── clean-css@4.2.1 
* node.js version - `node -v`: v6.16.0
* operating system: centOS

### Configuration options

```js
gulp.task('sass', function() {
	return gulp.src('./sass/sass.scss')
		.pipe(sourcemaps.init())
		.pipe( plumber( {errorHandler: onError } ) )
		.pipe(sass())
		//.pipe(autoPrefixer({ browsers: ['last 2 version', 'safari 5', 'ie 6', 'ie 7', 'ie 8', 'ie 9', 'opera 12.1', 'ios 6', 'android 4']}))
		.pipe( autoPrefixer( ) )
		.pipe( gulp.dest( './css') )
		.pipe( cleanCss({
		    //format: 'beautify', // formats output in a really nice way. When active, this line removes minification. 
		    level: { 
			1: {
			      cleanupCharsets: true, // controls `@charset` moving to the front of a stylesheet; defaults to `true`
			      normalizeUrls: true, // controls URL normalization; defaults to `true`
			      optimizeBackground: true, // controls `background` property optimizations; defaults to `true`
			      optimizeBorderRadius: true, // controls `border-radius` property optimizations; defaults to `true`
			      optimizeFilter: true, // controls `filter` property optimizations; defaults to `true`
			      optimizeFont: true, // controls `font` property optimizations; defaults to `true`
			      optimizeFontWeight: true, // controls `font-weight` property optimizations; defaults to `true`
			      optimizeOutline: true, // controls `outline` property optimizations; defaults to `true`
			      removeEmpty: true, // controls removing empty rules and nested blocks; defaults to `true`
			      removeNegativePaddings: true, // controls removing negative paddings; defaults to `true`
			      removeQuotes: true, // controls removing quotes when unnecessary; defaults to `true`
			      removeWhitespace: true, // controls removing unused whitespace; defaults to `true`
			      replaceMultipleZeros: true, // contols removing redundant zeros; defaults to `true`
			      replaceTimeUnits: true, // controls replacing time units with shorter values; defaults to `true`
			      replaceZeroUnits: true, // controls replacing zero values with units; defaults to `true`
			      roundingPrecision: true, // rounds pixel values to `N` decimal places; `false` disables rounding; defaults to `false`
			      selectorsSortingMethod: 'standard', // denotes selector sorting method; can be `'natural'` or `'standard'`, `'none'`, or false (the last two since 4.1.0); defaults to `'standard'`
			      specialComments: 'all', // denotes a number of /*! ... */ /* comments preserved; defaults to `all`*/
			      tidyAtRules: true, // controls at-rules (e.g. `@charset`, `@import`) optimizing; defaults to `true`
			      tidyBlockScopes: true, // controls block scopes (e.g. `@media`) optimizing; defaults to `true`
			      tidySelectors: true, // controls selectors optimizing; defaults to `true`,
			      semicolonAfterLastProperty: true, // controls removing trailing semicolons in rule; defaults to `false` - means remove
			      transform: function () {} // defines a callback for fine-grained property optimization; defaults to no-op
			    },
			  2: {
			      mergeAdjacentRules: false, // controls adjacent rules merging; defaults to true
			      mergeIntoShorthands: true, // controls merging properties into shorthands; defaults to true
			      mergeMedia: true, // controls `@media` merging; defaults to true
			      mergeNonAdjacentRules: true, // controls non-adjacent rule merging; defaults to true
			      mergeSemantically: false, // controls semantic merging; defaults to false
			      overrideProperties: true, // controls property overriding based on understandability; defaults to true
			      removeEmpty: true, // controls removing empty rules and nested blocks; defaults to `true`
			      reduceNonAdjacentRules: true, // controls non-adjacent rule reducing; defaults to true
			      removeDuplicateFontRules: true, // controls duplicate `@font-face` removing; defaults to true
			      removeDuplicateMediaBlocks: true, // controls duplicate `@media` removing; defaults to true
			      removeDuplicateRules: true, // controls duplicate rules removing; defaults to true
			      removeUnusedAtRules: true, // controls unused at rule removing; defaults to false (available since 4.1.0)
			      restructureRules: true, // controls rule restructuring; defaults to false
			      skipProperties: [] // controls which properties won't be optimized, defaults to `[]` which means all will be optimized (since 4.1.0)
			    }
		    }
		}) ) 
		.pipe( sourcemaps.write())
		.pipe( rename( { suffix: '.min' } ) )
		.pipe( gulp.dest( './css') )
		.pipe( notify( { message: 'SASS tasks complete' }))
});
```

### Input CSS

```css
header,
footer {
    display: none
}
```

### Actual output CSS

none

### Expected output CSS

header, footer {display:none}

**Comment by jakubpawlowicz** [comment]
I'm sorry it took me a while to have a look at it, but I cannot replicate it locally. Please reopen it if needed.
