### ISSUE TITLE
Build failed due to clean-css

### ISSUE THREAD

**Issue by hamze10** [jakubpawlowicz/clean-css#1129]
Hi,

I deployed successfuly an Angular 8 web application 3 months ago.
Today, I tried to push a new version but the build failed. But it's weird because I didn't add any dependencies

Here is the message : 
```json
21:48:20.496  	TypeError: value.replace is not a function
21:48:20.496  	    at tidyAtRule (/vercel/workpath0/node_modules/clean-css/lib/optimizer/level-1/tidy-at-rule.js:3:6)
21:48:20.496  	    at level1Optimize (/vercel/workpath0/node_modules/clean-css/lib/optimizer/level-1/optimize.js:639:47)
21:48:20.496  	    at optimize (/vercel/workpath0/node_modules/clean-css/lib/clean.js:144:5)
21:48:20.496  	    at /vercel/workpath0/node_modules/clean-css/lib/clean.js:120:29
21:48:20.496  	    at /vercel/workpath0/node_modules/clean-css/lib/reader/read-sources.js:26:64
21:48:20.496  	    at loadOriginalSources (/vercel/workpath0/node_modules/clean-css/lib/reader/load-original-sources.js:26:5)
21:48:20.496  	    at /vercel/workpath0/node_modules/clean-css/lib/reader/read-sources.js:26:14
21:48:20.496  	    at applySourceMaps (/vercel/workpath0/node_modules/clean-css/lib/reader/apply-source-maps.js:34:5)
21:48:20.496  	    at /vercel/workpath0/node_modules/clean-css/lib/reader/read-sources.js:25:12
21:48:20.496  	    at fromStyles (/vercel/workpath0/node_modules/clean-css/lib/reader/read-sources.js:152:5)
21:48:20.496  	    at fromString (/vercel/workpath0/node_modules/clean-css/lib/reader/read-sources.js:48:10)
21:48:20.496  	    at doReadSources (/vercel/workpath0/node_modules/clean-css/lib/reader/read-sources.js:33:12)
21:48:20.496  	    at readSources (/vercel/workpath0/node_modules/clean-css/lib/reader/read-sources.js:24:10)
21:48:20.496  	    at /vercel/workpath0/node_modules/clean-css/lib/clean.js:115:12
21:48:20.497  	    at processTicksAndRejections (internal/process/task_queues.js:79:11)
21:48:20.529  	npm ERR! code ELIFECYCLE
21:48:20.529  	npm ERR! errno 1
21:48:20.530  	npm ERR! xxx@0.0.0 build: `ng build --prod`
21:48:20.530  	npm ERR! Exit status 1
21:48:20.530  	npm ERR! 
21:48:20.530  	npm ERR! Failed at the xxx@0.0.0 build script.
21:48:20.531  	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
21:48:20.546  	npm ERR! A complete log of this run can be found in:
21:48:20.546  	npm ERR!     /vercel/.npm/_logs/2020-11-08T20_48_20_531Z-debug.log
21:48:20.551  	Error: Command "npm run build" exited with 1
21:48:23.827  	Done with "package.json"
```

And here is my package.json : 
```json
{
  "name": "xxx",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "compile:server": "webpack --config webpack.server.config.js --progress --colors",
    "serve:ssr": "node dist/server",
    "build:ssr": "npm run build:client-and-server-bundles && npm run compile:server",
    "build:client-and-server-bundles": "ng build --prod && ng run xxx--bundleDependencies all"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/platform-server": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@fortawesome/angular-fontawesome": "^0.5.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.28",
    "@fortawesome/free-brands-svg-icons": "^5.13.0",
    "@fortawesome/free-solid-svg-icons": "^5.13.0",
    "@nguniversal/express-engine": "^8.2.6",
    "@nguniversal/module-map-ngfactory-loader": "v8.2.6",
    "bulma": "^0.8.2",
    "express": "^4.15.2",
    "flag-icon-css": "^3.4.6",
    "rxjs": "~6.4.0",
    "tslib": "^1.13.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.26",
    "@angular/cli": "~8.3.23",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/express": "^4.17.6",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.2.2",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "protractor": "^5.4.4",
    "ts-loader": "^5.2.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3",
    "webpack-cli": "^3.3.11"
  }
}
```

Thank you !

**Comment by hamze10** [comment]
solved

**Comment by TheBrockEllis** [comment]
What solved your issue? Was it code-base specific? Placing the answer here, even if not entirely relevant to the library, could help future programmers with issues that they are struggling with.
