### ISSUE TITLE
Runtime error: Cannot read property 'bind' of undefined in latest Clean-CSS 5.0

### ISSUE THREAD

**Issue by vladmandic** [jakubpawlowicz/clean-css#1139]
Runtime error: Cannot read property 'bind' of undefined in latest Clean-CSS 5.0

Actual error stack:
```log
Client CSS build error TypeError: Cannot read property 'bind' of undefined
  at overrideProperties (/home/vlado/dev/pigallery/node_modules/clean-css/lib/optimizer/level-2/properties/override-properties.js:468:53)
  at optimizeProperties (/home/vlado/dev/pigallery/node_modules/clean-css/lib/optimizer/level-2/properties/optimize.js:33:5)
  at reduceSelector (/home/vlado/dev/pigallery/node_modules/clean-css/lib/optimizer/level-2/reduce-non-adjacent.js:161:3)
  at reduceSimpleNonAdjacentCases (/home/vlado/dev/pigallery/node_modules/clean-css/lib/optimizer/level-2/reduce-non-adjacent.js:82:5)
  at reduceNonAdjacent (/home/vlado/dev/pigallery/node_modules/clean-css/lib/optimizer/level-2/reduce-non-adjacent.js:54:3)
  at level2Optimize (/home/vlado/dev/pigallery/node_modules/clean-css/lib/optimizer/level-2/optimize.js:89:5)
  at optimize (/home/vlado/dev/pigallery/node_modules/clean-css/lib/clean.js:221:5)
  at /home/vlado/dev/pigallery/node_modules/clean-css/lib/clean.js:194:29
  at /home/vlado/dev/pigallery/node_modules/clean-css/lib/reader/read-sources.js:26:64
  at loadOriginalSources (/home/vlado/dev/pigallery/node_modules/clean-css/lib/reader/load-original-sources.js:26:5)
```

Code where this happens is in `clean-css/lib/optimizer/level-2/properties/override-properties.js`  
```js
mayOverride = configuration[right.name].canOverride;
overridable = everyValuesPair(mayOverride.bind(null, validator), left, right);
```

I've added a debug output just to check values:
```js
console.log('clean-css debug:', right.name, configuration[right.name], configuration[right.name].canOverride);
```

And for most entries it passes without errors.
However, for `right.name === clip`, there are no defaults and property `canOverride` is not defined.

```js
clean-css debug: clip {
  valueOptimizers: [
    [Function: whitespace],
    [Function: fraction],
    [Function: precision],
    [Function: unit],
    [Function: zero]
  ]
} undefined
```

Configuration is:
```js
  clean = new CleanCSS({ level: { 1: { all: true }, 2: { all: true } } });
```

And actual CSS is at: <https://github.com/vladmandic/pigallery/blob/master/client/pigallery.css>

I've added a quick workaround with, but that's not a solution:
```js
  overridable = mayOverride ? everyValuesPair(mayOverride.bind(null, validator), left, right) : true;
```

Environment
- Clean-CSS 5.0
- NodeJS 15.7.0
- OS: Ubuntu 20.10

**Comment by jakubpawlowicz** [comment]
Thanks @vladmandic, stellar bug report! I'll have a look in a moment.

**Comment by jakubpawlowicz** [comment]
Hey @vladmandic - I cannot replicate it locally.  When I optimize `pigallery.css` it throws no errors.

Are you sure it's a right CSS as `pigallery.css` doesn't have a `clip` element at all?

**Comment by vladmandic** [comment]
That's the only application CSS file, but there are additional CSS files combined with it from couple of 3rd party libraries:
```js
const cssFiles = ['assets/bootstrap.css', 'assets/fontawesome.css', 'client/index/iv-viewer.css', 'assets/mapquest.css', 'client/pigallery.css'];
```
they are all accessible from project root <https://github.com/vladmandic/pigallery>

**Comment by jakubpawlowicz** [comment]
Gotcha!

**Comment by vladmandic** [comment]
fyi, actual code (simplified) that combines the cssFiles:
```js
    const clean = new CleanCSS({ level: { 1: { all: true }, 2: { all: true } } });
    const cssFiles = ['assets/bootstrap.css', 'assets/fontawesome.css', 'client/index/iv-viewer.css', 'assets/mapquest.css', 'client/pigallery.css'];
    const data = [];
    for (let i = 0; i < cssFiles.length; i++) {
      if (fs.existsSync(cssFiles[i])) {
        const styles = fs.readFileSync(cssFiles[i], 'utf-8');
        const obj = {};
        obj[cssFiles[i]] = { styles };
        data.push(obj);
      }
    }
    const css = clean.minify(data);
    fs.writeFileSync('dist/pigallery.css', css.styles);
```

**Comment by jakubpawlowicz** [comment]
Thanks @vladmandic - the fix is ready. It was only possible to see it once files were combined, but actually the reduced test case was very very short. Going to release 5.0.1 shortly.

**Comment by jakubpawlowicz** [comment]
5.0.1 is out with the fix. :beer: for early testing!

**Comment by vladmandic** [comment]
confirmed as resolved - thanks!

**Comment by jakubpawlowicz** [comment]
Great 👍
