### ISSUE TITLE
Error in level 2 optimizations with a trailing comma in a property

### ISSUE THREAD

**Issue by gherkz** [jakubpawlowicz/clean-css#1166]
### Precheck
 
* Do a quick search and make sure a bug has not yet been reported; 👍
* do a quick check if the bug still exists in the latest patch version; 👍
* finally, be nice and have fun! 👍

### Environment

* clean-css version - `npm ls clean-css`: 5.1.2
* node.js version - `node -v`: v16.0.0
* operating system: macOS Big Sur

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
  level: 2
})
```

### Input CSS

```css
div { background: black,; }
```

### Actual output CSS

```
Uncaught TypeError: Cannot read property '2' of undefined
    at background (.../node_modules/clean-css/lib/optimizer/configuration/break-up.js:223:93)
    at Object.breakUp (.../node_modules/clean-css/lib/optimizer/configuration/break-up.js:467:30)
    at populateComponents (.../node_modules/clean-css/lib/optimizer/level-2/properties/populate-components.js:22:42)
    at optimizeProperties (.../node_modules/clean-css/lib/optimizer/level-2/properties/optimize.js:19:3)
    at recursivelyOptimizeProperties (.../node_modules/clean-css/lib/optimizer/level-2/optimize.js:63:9)
    at level2Optimize (.../node_modules/clean-css/lib/optimizer/level-2/optimize.js:78:3)
    at optimize (.../node_modules/clean-css/lib/clean.js:221:5)
    at .../node_modules/clean-css/lib/clean.js:194:29

```

### Expected output CSS

```css
div{background:#000}
```

I'm sure that the input CSS isn't actually correct syntax, but it would be nice to be able to gracefully handle this scenario. I'll submit a PR for it shortly.

**Comment by jakubpawlowicz** [comment]
Released in 5.1.3, thanks for the fix!
