### ISSUE TITLE
cleancss crashes with --source-map option.

### ISSUE THREAD

**Issue by brshewmaker** [jakubpawlowicz/clean-css#469]
Trying to call cleancss with --source-map causes it to crash.  

```shell
cleancss --source-map --output style.min.css style.css

/usr/local/lib/node_modules/clean-css/lib/properties/extractor.js:47
  return name.replace(/^\-\w+\-/, '').match(/([a-z]+)/)[0];
                                                       ^
TypeError: Cannot read property '0' of null
    at findNameRoot (/usr/local/lib/node_modules/clean-css/lib/properties/extractor.js:47:56)
    at extract (/usr/local/lib/node_modules/clean-css/lib/properties/extractor.js:17:22)
    at AdvancedOptimizer.restructure (/usr/local/lib/node_modules/clean-css/lib/selectors/optimizers/advanced.js:598:22)
    at _optimize (/usr/local/lib/node_modules/clean-css/lib/selectors/optimizers/advanced.js:722:12)
    at /usr/local/lib/node_modules/clean-css/lib/selectors/optimizers/advanced.js:708:9
    at Array.forEach (native)
    at _optimize (/usr/local/lib/node_modules/clean-css/lib/selectors/optimizers/advanced.js:705:12)
    at AdvancedOptimizer.optimize (/usr/local/lib/node_modules/clean-css/lib/selectors/optimizers/advanced.js:734:3)
    at SelectorsOptimizer.process (/usr/local/lib/node_modules/clean-css/lib/selectors/optimizer.js:15:55)
    at /usr/local/lib/node_modules/clean-css/lib/clean.js:174:31
```

Running it without the `--source-map` option, it works as expected.  

```
cleancss -v
3.1.0
```

**Comment by jakubpawlowicz** [comment]
@brshewmaker Would you be able to share your sources, so I can try on my own? It was suggested that https://github.com/jonathanepollack/gulp-minify-css/issues/70#issuecomment-76262887 is the cause, but not likely since that code does property not selector matching.

In the meantime you can use `restructuring: false` switch which disables that part of the code.

**Comment by WRidder** [comment]
@jakubpawlowicz I encountered the same error. You could try it with: https://github.com/WRidder/react-spa/. Use `gulp build --release`.

**Comment by jakubpawlowicz** [comment]
Will do, stay tuned!

**Comment by jakubpawlowicz** [comment]
It should work well with just-released clean-css 3.1.1.

@WRidder Please note you may have an issue with gulpfile as it's clearly pumping SASS files into clean-css, which should not really be the case.

**Comment by WRidder** [comment]
@jakubpawlowicz Thanks for the heads up!

**Comment by michailw** [comment]
I had discovered this issue about week ago, so I think happens again.

**Comment by jakubpawlowicz** [comment]
@michailw Could you please share more info as described in https://github.com/jakubpawlowicz/clean-css/blob/master/CONTRIBUTING.md

**Comment by michailw** [comment]
Sorry, I haven't read this document before.

This is code which I try to run:

```js
var gulp = require('gulp'),
    gutil = require('gulp-util'),
    sh = require('shelljs'),
    minifyCSS = require('gulp-minify-css'),
    concat    = require('gulp-concat'),
    sourcemaps = require('gulp-sourcemaps'),
    rename    = require('gulp-rename'),
    fs = require('fs'),
    ini = require('ini'),
    md5File = require('gulp-md5'),
    del = require('del'),
    uglify = require('gulp-uglify'),
    jsValidate = require('gulp-jsvalidate'),
    through = require('through2'),
    PluginError = gutil.PluginError,
    path = require('path')
;

var config = ini.parse(fs.readFileSync(paths.config.assets, 'utf-8'));

    var styles = [];
    for(var i in config.styles){
        if(
            config.styles.hasOwnProperty(i) && i!='length'
            && config.styles[i].substr(0, 4) != 'http' && config.styles[i].substr(0, 2) != '//'
        ){
            styles.push(paths.assets.static+config.styles[i]);
        }
    }

    var a={};
    return gulp
        .src(styles)
        .pipe(sourcemaps.init())
        .pipe(concat('style.css'))
        .pipe(gulp.dest(paths.assets.temp))
        .pipe(minifyCSS({keepBreaks:false}))
        .pipe(md5File())
        .pipe(md5Checksum(a))
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest(paths.assets.stylesMin))
        .on('finish', function() {
            var fileHash = a.path.split('.');
            fileHash = fileHash[0];
            return fs.readFile(paths.config.app, 'utf8', function (err,data) {
                if (err) return console.log(err);
                var result = data.replace(/^\s*compressed\.cssHash.*$/gm, 'compressed.cssHash = "'+fileHash+'"');

                fs.writeFile(paths.config.app, result, 'utf8', function (err) {
                    if (err) return console.log(err);
                });
            });
        });
    ;
```

This is console output:

```
/var/www/node_modules/gulp-minify-css/node_modules/clean-css/lib/text/escape-store.js:49
  var index = this.restoreMatcher.exec(placeholder)[1];
                                                   ^
TypeError: Cannot read property '1' of null
    at EscapeStore.restore (/var/www/node_modules/gulp-minify-css/node_modules/clean-css/lib/text/escape-store.js:49:52)
    at restore (/var/www/node_modules/gulp-minify-css/node_modules/clean-css/lib/text/comments-processor.js:109:24)
    at CommentsProcessor.restore (/var/www/node_modules/gulp-minify-css/node_modules/clean-css/lib/text/comments-processor.js:128:10)
    at Object.restore (/var/www/node_modules/gulp-minify-css/node_modules/clean-css/lib/clean.js:198:32)
    at store (/var/www/node_modules/gulp-minify-css/node_modules/clean-css/lib/stringifier/source-maps.js:12:21)
    at property (/var/www/node_modules/gulp-minify-css/node_modules/clean-css/lib/stringifier/helpers.js:86:5)
    at body (/var/www/node_modules/gulp-minify-css/node_modules/clean-css/lib/stringifier/helpers.js:77:5)
    at all (/var/www/node_modules/gulp-minify-css/node_modules/clean-css/lib/stringifier/helpers.js:140:9)
    at stringify (/var/www/node_modules/gulp-minify-css/node_modules/clean-css/lib/stringifier/source-maps.js:74:3)
    at SelectorsOptimizer.process (/var/www/node_modules/gulp-minify-css/node_modules/clean-css/lib/selectors/optimizer.js:19:10)

npm ERR! Linux 2.6.32-431.17.1.el6.x86_64
npm ERR! argv "/opt/iojs-v2.0.1/bin/iojs" "/usr/bin/npm" "run" "gulp" "minify-css"
npm ERR! node v2.0.1
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE
npm ERR! Sofait.pl@1.0.0 gulp: `gulp "minify-css"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Sofait.pl@1.0.0 gulp script 'gulp "minify-css"'.
npm ERR! This is most likely a problem with the Sofait.pl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp "minify-css"
npm ERR! You can get their info via:
npm ERR!     npm owner ls Sofait.pl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/npm-debug.log
```

When I comment lines `.pipe(sourcemaps.init())` and `.pipe(sourcemaps.write('./'))`, it works.

npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/opt/iojs-v2.0.1/bin/iojs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'gulp',
1 verbose cli   'minify-css' ]
2 info using npm@2.9.0
3 info using node@v2.0.1
4 verbose run-script [ 'pregulp', 'gulp', 'postgulp' ]
5 info pregulp MojProjekt.JS@1.0.0
6 info gulp MojProjekt.JS@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info MojProjekt.JS@1.0.0 Failed to exec gulp script
9 verbose stack Error: MojProjekt.JS@1.0.0 gulp: `gulp "minify-css"`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/opt/iojs-v2.0.1/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:169:7)
9 verbose stack     at ChildProcess.<anonymous> (/opt/iojs-v2.0.1/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:169:7)
9 verbose stack     at maybeClose (child_process.js:953:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1020:5)
10 verbose pkgid MojProjekt.JS@1.0.0
11 verbose cwd /var/www
12 error Linux 2.6.32-431.17.1.el6.x86_64
13 error argv "/opt/iojs-v2.0.1/bin/iojs" "/usr/bin/npm" "run" "gulp" "minify-css"
14 error node v2.0.1
15 error npm  v2.9.0
16 error code ELIFECYCLE
17 error MojProjekt.JS@1.0.0 gulp: `gulp "minify-css"`
17 error Exit status 1
18 error Failed at the MojProjekt.JS@1.0.0 gulp script 'gulp "minify-css"'.
18 error This is most likely a problem with the MojProjekt.JS package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp "minify-css"
18 error You can get their info via:
18 error     npm owner ls MojProjekt.JS
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by jakubpawlowicz** [comment]
@michailw sorry, but I didn't have a chance to get back to you sooner. I'll open it as a separate issue as it's clearly sth different than the original one.
