### ISSUE TITLE
error using source map

### ISSUE THREAD

**Issue by mhf-ir** [jakubpawlowicz/clean-css#510]
```
cleancss --source-map --output public/lib/css/bootstrap.min.css public/lib/css/bootstrap.css 
fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/home/sweb/project1/public/lib/css/bootstrap.css.map'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at fromSource (/home/sweb/project1/node_modules/clean-css/lib/utils/input-source-map-tracker.js:67:31)
    at InputSourceMapStore.track (/home/sweb/project1/node_modules/clean-css/lib/utils/input-source-map-tracker.js:137:5)
    at Object.whenDone (/home/sweb/project1/node_modules/clean-css/lib/clean.js:100:44)
    at processNext (/home/sweb/project1/node_modules/clean-css/lib/imports/inliner.js:103:35)
    at importFrom (/home/sweb/project1/node_modules/clean-css/lib/imports/inliner.js:77:10)
    at processNext (/home/sweb/project1/node_modules/clean-css/lib/imports/inliner.js:102:41)
    at importFrom (/home/sweb/project1/node_modules/clean-css/lib/imports/inliner.js:77:10)
```
nodeversion : v0.12.2
cleancss -v 3.1.8

**Comment by mhf-ir** [comment]
same error on node v0.10.32 :cry:

**Comment by jakubpawlowicz** [comment]
@mhf-ir it fails because, presumably, your bootstrap.css references `bootstrap.css.map` file (see the very end of the file).

I think the error should be more self-explanatory though.

**Comment by mhf-ir** [comment]
:+1: it's okay but how can i minify the css with source-map comment ?
how can i skip this ? bootstrap source file (not minified version) has source map comment.

**Comment by jakubpawlowicz** [comment]
@mhf-ir you need to either 1) remove source map comment 2) put bootstrap.css.map in the same folder as bootstrap.css.

**Comment by jakubpawlowicz** [comment]
Please reopen if needed.
