### ISSUE TITLE
HTTP @import after No-URL @import causes an error

### ISSUE THREAD

**Issue by shinnn** [jakubpawlowicz/clean-css#580]
### Versions

This test uses the current [`master`](https://github.com/jakubpawlowicz/clean-css/tree/master) branch (not v3.2.10 on npm).

```
$ npm install jakubpawlowicz/clean-css#ea1e42324ea6404bde9e624bd1670ecd0ecd6a36
clean-css@3.3.0-pre node_modules/clean-css
├── commander@2.8.1 (graceful-readlink@1.0.1)
└── source-map@0.4.2 (amdefine@0.1.0)
$ node -v
v2.0.2
```

### CSS File

./external.css

```css
a { color: red; }
```

### Test script 1: HTTP `@import` after `url("external.css")` :o:

```js
'use strict';

var CleanCSS = require('clean-css');

var files = {
  'main.css': {
    styles: [
      '@import url("external.css)";',
      '@import url("http://fonts.googleapis.com/css?family=Open+Sans");'
    ].join('\n')
  }
};

var result = new CleanCSS().minify(files, function(err) {
  console.log(err); //=> null
});
```

It doesn't throw any errors.

### Test script 2: HTTP `@import` after `"external.css"` :x: 

```js
'use strict';

var CleanCSS = require('clean-css');

var files = {
  'main.css': {
    styles: [
      '@import "external.css";',
      '@import url("http://fonts.googleapis.com/css?family=Open+Sans");'
    ].join('\n')
  }
};

var result = new CleanCSS().minify(files, function(err) {
  console.log(err);
});
```

It throws the following error:

```
/Users/Shinnosuke/github/test/node_modules/clean-css/lib/tokenizer/tokenize.js:204
        context.source = oldState.source;
                                 ^
TypeError: Cannot read property 'source' of undefined
    at intoTokens (/Users/Shinnosuke/github/test/node_modules/clean-css/lib/tokenizer/tokenize.js:204:34)
    at tokenize (/Users/Shinnosuke/github/test/node_modules/clean-css/lib/tokenizer/tokenize.js:38:10)
    at SelectorsOptimizer.process (/Users/Shinnosuke/github/test/node_modules/clean-css/lib/selectors/optimizer.js:12:16)
    at /Users/Shinnosuke/github/test/node_modules/clean-css/lib/clean.js:192:31
    at run (/Users/Shinnosuke/github/test/node_modules/clean-css/lib/clean.js:179:7)
    at minify (/Users/Shinnosuke/github/test/node_modules/clean-css/lib/clean.js:191:3)
    at whenSourceMapReady (/Users/Shinnosuke/github/test/node_modules/clean-css/lib/clean.js:109:7)
    at Object.whenDone (/Users/Shinnosuke/github/test/node_modules/clean-css/lib/clean.js:129:14)
    at processNext (/Users/Shinnosuke/github/test/node_modules/clean-css/lib/imports/inliner.js:104:35)
    at importFrom (/Users/Shinnosuke/github/test/node_modules/clean-css/lib/imports/inliner.js:78:10)
```

**Comment by jakubpawlowicz** [comment]
Fixed in master. Very nice bug report :+1:

**Comment by shinnn** [comment]
Thanks always :)
