### ISSUE TITLE
Breaking change in 3.3.8 (handling data URI with brackets)

### ISSUE THREAD

**Issue by gregersrygg** [jakubpawlowicz/clean-css#640]
The commit for handling data URI with brackets (2028fad) introduced a breaking change.

```bash
...
[11:36:32] Starting 'minify-stylesheets'...

/Users/figrrygg/devel/spaden/node_modules/gulp-minify-css/node_modules/clean-css/lib/text/escape-store.js:49
  var index = this.restoreMatcher.exec(placeholder)[1];
                                                   ^
TypeError: Cannot read property '1' of null
    at EscapeStore.restore (/Users/figrrygg/devel/spaden/node_modules/gulp-minify-css/node_modules/clean-css/lib/text/escape-store.js:49:52)
    at restore (/Users/figrrygg/devel/spaden/node_modules/gulp-minify-css/node_modules/clean-css/lib/text/comments-processor.js:109:24)
    at CommentsProcessor.restore (/Users/figrrygg/devel/spaden/node_modules/gulp-minify-css/node_modules/clean-css/lib/text/comments-processor.js:128:10)
    at Object.restore (/Users/figrrygg/devel/spaden/node_modules/gulp-minify-css/node_modules/clean-css/lib/clean.js:198:32)
    at store (/Users/figrrygg/devel/spaden/node_modules/gulp-minify-css/node_modules/clean-css/lib/stringifier/source-maps.js:12:21)
    at value (/Users/figrrygg/devel/spaden/node_modules/gulp-minify-css/node_modules/clean-css/lib/stringifier/helpers.js:102:5)
    at property (/Users/figrrygg/devel/spaden/node_modules/gulp-minify-css/node_modules/clean-css/lib/stringifier/helpers.js:91:5)
    at body (/Users/figrrygg/devel/spaden/node_modules/gulp-minify-css/node_modules/clean-css/lib/stringifier/helpers.js:77:5)
    at all (/Users/figrrygg/devel/spaden/node_modules/gulp-minify-css/node_modules/clean-css/lib/stringifier/helpers.js:140:9)
    at stringify (/Users/figrrygg/devel/spaden/node_modules/gulp-minify-css/node_modules/clean-css/lib/stringifier/source-maps.js:74:3)
```

We use clean-css through gulp-minify-css, but I was able to reproduce the bug from command-line (see below).
Operating system: OS X Yosemite (10.10.3)

I tried to write a test that fails, but wasn't able to reproduce the error from a test. But if you create a file with the content below, and run this command: `cleancss --source-map test.css -o test.min.css`, it should throw the error.

```css
a{background: url('img.gif');/* x */}
```

**Comment by jakubpawlowicz** [comment]
I can see it happening indeed. Without source map it's fine though. Fix is coming.

**Comment by jakubpawlowicz** [comment]
Fixed in 3.3.9.

**Comment by gregersrygg** [comment]
Wow, that was quick! Thanks :smile:

**Comment by jakubpawlowicz** [comment]
Sure, anytime :-)
