### ISSUE TITLE
clean-css  Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by artyfarty** [jakubpawlowicz/clean-css#652]
Our builds are suddenly broken (as gulp-cssmin updated internal `clean-css@3.3.9` -> `clean-css@3.4.0`)

```
PATH_GOES_HERE/node_modules/gulp-cssmin/node_modules/clean-css/lib/properties/restore-from-optimizing.js:53
	    current[0][0] = property.name;
	           ^
	TypeError: Cannot read property '0' of undefined
	    at restoreFromOptimizing (PATH_GOES_HERE/node_modules/gulp-cssmin/node_modules/clean-css/lib/properties/restore-from-optimizing.js:53:12)
	    at optimizeBody (PATH_GOES_HERE/node_modules/gulp-cssmin/node_modules/clean-css/lib/selectors/simple.js:352:3)
	    at optimize (PATH_GOES_HERE/node_modules/gulp-cssmin/node_modules/clean-css/lib/selectors/simple.js:418:9)
	    at minify (PATH_GOES_HERE/node_modules/gulp-cssmin/node_modules/clean-css/lib/clean.js:225:3)
	    at whenSourceMapReady (PATH_GOES_HERE/node_modules/gulp-cssmin/node_modules/clean-css/lib/clean.js:135:7)
	    at Object.whenDone (PATH_GOES_HERE/node_modules/gulp-cssmin/node_modules/clean-css/lib/clean.js:155:14)
	    at processNext (PATH_GOES_HERE/node_modules/gulp-cssmin/node_modules/clean-css/lib/imports/inliner.js:105:35)
	    at importFrom (PATH_GOES_HERE/node_modules/gulp-cssmin/node_modules/clean-css/lib/imports/inliner.js:79:10)
	    at ImportInliner.process (PATH_GOES_HERE/node_modules/gulp-cssmin/node_modules/clean-css/lib/imports/inliner.js:38:10)
	    at PATH_GOES_HERE/node_modules/gulp-cssmin/node_modules/clean-css/lib/clean.js:120:41
```

I still have no idea what in the stream causes this problem.

**Comment by jakubpawlowicz** [comment]
No idea as well as all tests are green.

**Comment by michael-zucchetta** [comment]
I was coming here to post the very same thing. 

I am not able to run `gulp-minify-css` after it uploaded `clean-css` to version `3.4.0`. I have the exact trace

**Comment by firegnom** [comment]
not 100% sure but i think it is failing on : 

```
.fail {
    *cursor: hand;
    color: #111 !important;
}
```

value of current is undefined ,

value of property is :
```
block: false,
  components: [],
  dirty: false,
  hack: false,
  important: true,
  name: 'color',
  multiplex: false,
  position: 1,
  shorthand: false,
  unused: false,
  value: [ [ '#111!important' ] ],
  variable: false,
  all: [ [ [Object], [Object] ] ] }
```

you can see that  all has only one object inside and the position of current property is 1 and it should be 0
it looks that after running ie hack for line ``` *cursor: hand;``` this line is removed from properties after that  the properties should be reindexed

**Comment by jakubpawlowicz** [comment]
It could be it. Let's give it a try.

**Comment by jakubpawlowicz** [comment]
Can someone try the latest version on 3.4 branch?

This reason of this bug is quite stupid, as we were doing operations in the wrong order...

**Comment by sjparkinson** [comment]
Seems to have worked for us (using `"clean-css": "git+https://github.com/jakubpawlowicz/clean-css.git#3.4"`):

![screen shot 2015-08-27 at 2 41 52 pm](https://cloud.githubusercontent.com/assets/51677/9521962/cb1dfede-4cc9-11e5-9afb-8a01c50c4508.png)

vs. without:

![screen shot 2015-08-27 at 2 41 59 pm](https://cloud.githubusercontent.com/assets/51677/9521960/c78bf1d6-4cc9-11e5-82b5-40a8b815c8cc.png)

**Comment by artyfarty** [comment]
Do you have a test for another old hack — `_property:`?

**Comment by jakubpawlowicz** [comment]
@sjparkinson thanks, will push 3.4.1 soon
@artyfarty if you mean this particular case, there's no, but in general there are quite a few for underscore hack - https://github.com/jakubpawlowicz/clean-css/blob/master/test/selectors/simple-test.js#L379 and more for advanced optimizations

**Comment by jakubpawlowicz** [comment]
Released as 3.4.1 - thanks for all the help @artyfarty @sjparkinson @firegnom @michael-zucchetta !

**Comment by artyfarty** [comment]
All good now, thanks!

I'll use `npm shrinkwrap` from now on though...

**Comment by jakubpawlowicz** [comment]
Always a good idea :+1:
