### ISSUE TITLE
Unhelpful error message on invalid CSS syntax

### ISSUE THREAD

**Issue by chernetsov0** [jakubpawlowicz/clean-css#657]
For example for following invalid syntax:

``` css
.panel {
    -webkit-: 0 0 2px rgba(#000, 0.4);
}
```

You'll receive:

```
TypeError: Cannot read property '0' of null
    at findNameRoot (clean-css\lib\selectors\extractor.js:58:59)
    at extract (clean-css\lib\selectors\extractor.js:28:9)
    at AdvancedOptimizer.restructure (clean-css\lib\selectors\optimizers\advanced.js:651:22)
    at _optimize (clean-css\lib\selectors\optimizers\advanced.js:835:12)
    at AdvancedOptimizer.optimize (clean-css\lib\selectors\optimizers\advanced.js:850:3)
    at SelectorsOptimizer.process (clean-css\lib\selectors\optimizer.js:17:55)
    at clean-css\lib\clean.js:193:31
    at run (clean-css\lib\clean.js:180:7)
    at minify (clean-css\lib\clean.js:192:3)
    at whenSourceMapReady (clean-css\lib\clean.js:110:7)
```

which is as unhelpful as error could get. Probably syntax parser should at least indicate that it is a syntax error and file name + line number? Type of error is secondary really and could be added incrementally.

**Comment by jakubpawlowicz** [comment]
CSS does not have a well defined property syntax, so basically you can pass anything and whatever browsers do not understand will be dropped. clean-css does not aim to cover all these cases on parsing level.

In this case it simply tries to extract property name without a prefix and fails. This is something that should be fixed.

**Comment by jakubpawlowicz** [comment]
Raising valuable warnings on invalid property names is now on master. Sorry it took a bit.

**Comment by chernetsov0** [comment]
@jakubpawlowicz it took me a bit to notice too. 😄 Thanks a lot!
