### ISSUE TITLE
Error during Uri rewrite in Node v4.0.0

### ISSUE THREAD

**Issue by bassarisse** [jakubpawlowicz/clean-css#671]
Hi!

I'm currently using Node v4.0.0 and the following error appears to me:
```
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.join (path.js:221:5)
    at relative (C:\Users\GAtec\Desktop\Bruno\Projects\LMS-AISE-Social\node_modules\gulp-minify-css\node_modules\clean-css\lib\urls\rewrite.js:43:45)
    at rebase (C:\Users\GAtec\Desktop\Bruno\Projects\LMS-AISE-Social\node_modules\gulp-minify-css\node_modules\clean-css\lib\urls\rewrite.js:71:15)
    at C:\Users\GAtec\Desktop\Bruno\Projects\LMS-AISE-Social\node_modules\gulp-minify-css\node_modules\clean-css\lib\urls\rewrite.js:88:44
    at byUrl (C:\Users\GAtec\Desktop\Bruno\Projects\LMS-AISE-Social\node_modules\gulp-minify-css\node_modules\clean-css\lib\urls\reduce.js:72:5)
    at reduceAll (C:\Users\GAtec\Desktop\Bruno\Projects\LMS-AISE-Social\node_modules\gulp-minify-css\node_modules\clean-css\lib\urls\reduce.js:145:10)
    at rewriteUrls (C:\Users\GAtec\Desktop\Bruno\Projects\LMS-AISE-Social\node_modules\gulp-minify-css\node_modules\clean-css\lib\urls\rewrite.js:86:10)
    at IncomingMessage.<anonymous> (C:\Users\GAtec\Desktop\Bruno\Projects\LMS-AISE-Social\node_modules\gulp-minify-css\node_modules\clean-css\lib\imports\inliner.js:311:24)
    at emitNone (events.js:72:20)
```

I fixed by changing the following on `lib/urls/rewrite.js` (line 42):
```javascript
function relative(uri, options) {
  return path.relative(options.toBase, path.join(options.fromBase || "", uri));
}
```

Is this the best way to resolve the issue?
It might be important to note that I'm using CleanCSS through gulp-minify-css.

Thanks!

**Comment by bassarisse** [comment]
Sorry, just saw the coomit fixing this, thanks!

**Comment by jakubpawlowicz** [comment]
No worries! :+1:
