### ISSUE TITLE
"TypeError: Path must be a string. Received undefined" on node 6.0.0

### ISSUE THREAD

**Issue by gkorland** [jakubpawlowicz/clean-css#769]
It seems like fromString always pass undefined as the sourcepath

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at /home/guy/WebstormProjects/selfpointrest/node_modules/clean-css/lib/utils/input-source-map-tracker.js:192:56
    at Array.forEach (native)
    at trackContentSources (/home/guy/WebstormProjects/selfpointrest/node_modules/clean-css/lib/utils/input-source-map-tracker.js:189:20)
    at InputSourceMapStore.trackLoaded (/home/guy/WebstormProjects/selfpointrest/node_modules/clean-css/lib/utils/input-source-map-tracker.js:256:3)
    at fromString (/home/guy/WebstormProjects/selfpointrest/node_modules/clean-css/lib/utils/input-source-map-tracker.js:32:8)
    at InputSourceMapStore.track (/home/guy/WebstormProjects/selfpointrest/node_modules/clean-css/lib/utils/input-source-map-tracker.js:237:5)
    at Object.whenDone (/home/guy/WebstormProjects/selfpointrest/node_modules/clean-css/lib/clean.js:145:44)
    at processNext (/home/guy/WebstormProjects/selfpointrest/node_modules/clean-css/lib/imports/inliner.js:105:13)
    at importFrom (/home/guy/WebstormProjects/selfpointrest/node_modules/clean-css/lib/imports/inliner.js:79:10)
    at processNext (/home/guy/WebstormProjects/selfpointrest/node_modules/clean-css/lib/imports/inliner.js:104:16)
    at importFrom (/home/guy/WebstormProjects/selfpointrest/node_modules/clean-css/lib/imports/inliner.js:79:10)
    at /home/guy/WebstormProjects/selfpointrest/node_modules/clean-css/lib/imports/inliner.js:325:9
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

**Comment by scniro** [comment]
@gkorland are you using gulp with this? See [this resolved issue](https://github.com/scniro/gulp-clean-css/issues/4) if so.

**Comment by gkorland** [comment]
@scniro thanks it solved it, but don't you think that anyway this bug should be fixed this package?

**Comment by jakubpawlowicz** [comment]
Fixed in #774 and 3.4.13.

**Comment by scniro** [comment]
gulp-clean-css 2.0.8 has been published with the 3.4.13 dep 32909e1eed30a536175afd2aa7d26727877a025a

**Comment by jakubpawlowicz** [comment]
👍

**Comment by srikanthenjamoori** [comment]
I'm using grunt, and got the same issue.
