### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by JonWallsten** [jakubpawlowicz/clean-css#777]
Hi!
I've been using this tool for a long time, and this is the first time it happened.
Same steps as always. Not sure whats wrong.
```
[exec] [10:20:37] 'clean' errored after 685 ╬╝s
[exec] [10:20:37] TypeError: Cannot read property '0' of undefined
[exec]     at isNegative (E:\build\*****\node_modules\globby\index.js:12:16)
[exec]     at Array.filter (native)
[exec]     at E:\build\*****\node_modules\globby\index.js:26:34
[exec]     at Array.forEach (native)
[exec]     at generateGlobTasks (E:\build\*****\node_modules\globby\index.js:21:11)
[exec]     at module.exports (E:\build\*****\node_modules\globby\index.js:42:18)
[exec]     at Object.module.exports [as del] (E:\build\*****\node_modules\del\index.js:31:9)
[exec]     at Gulp.<anonymous> (E:\build\*****\gulpfile.js:240:18)
[exec]     at module.exports (E:\build\*****\node_modules\orchestrator\lib\runTask.js:34:7)
[exec]     at Gulp.Orchestrator._runTask (E:\build\*****\node_modules\orchestrator\index.js:273:3)
[exec] [10:20:37] Error in plugin 'run-sequence'
[exec] Message:
[exec]     An error occured in task 'clean'.
[exec] [10:20:37] Finished 'build' after 5.31 ms
```

**Comment by JonWallsten** [comment]
Turned out I tried to remove "undefined". Used a variable that didn't exist any more as a folder.

**Comment by jakubpawlowicz** [comment]
It doesn't look like tied to clean-css but glad you found the solution. Closing for now!
