### ISSUE TITLE
I dont know why toRemove return undefined

### ISSUE THREAD

**Issue by zodman** [jakubpawlowicz/clean-css#800]
at 

 https://github.com/jakubpawlowicz/clean-css/blob/master/lib/properties/optimizer.js#L133

i fix with:

```
if ( typeof(toRemove) != 'undefined') {
    var longhandToShorthand = toRemove.name != _name;
} else {    
 continue;
}

```

**Comment by jakubpawlowicz** [comment]
It certainly should not be `undefined`, so your code snippet is worth having. However a reproducible test case would definitely be great to have - see https://github.com/jakubpawlowicz/clean-css/blob/master/CONTRIBUTING.md#pull-requests

**Comment by analytik** [comment]
Seems to work in Node.js v4.4.x, broken in 6.5, 6.6 and possibly others.

**Comment by acidjazz** [comment]
confirmed w/ v6.9.1

/Users/k/256/node_modules/clean-css/lib/properties/optimizer.js:134
        var longhandToShorthand = toRemove.name != _name;
                                          ^

TypeError: Cannot read property 'name' of undefined
  at _optimize (/Users/k/256/node_modules/clean-css/lib/properties/optimizer.js:134:43)
  at optimize (/Users/k/256/node_modules/clean-css/lib/properties/optimizer.js:198:3)
  at recursivelyOptimizeProperties (/Users/k/256/node_modules/clean-css/lib/selectors/advanced.js:51:9)
  at optimize (/Users/k/256/node_modules/clean-css/lib/selectors/advanced.js:61:3)
  at minify (/Users/k/256/node_modules/clean-css/lib/clean.js:228:5)
  at whenSourceMapReady (/Users/k/256/node_modules/clean-css/lib/clean.js:135:7)
  at Object.whenDone (/Users/k/256/node_modules/clean-css/lib/clean.js:155:14)
  at processNext (/Users/k/256/node_modules/clean-css/lib/imports/inliner.js:105:13)
  at importFrom (/Users/k/256/node_modules/clean-css/lib/imports/inliner.js:79:10)
  at ImportInliner.process (/Users/k/256/node_modules/clean-css/lib/imports/inliner.js:38:10)
  at /Users/k/256/node_modules/clean-css/lib/clean.js:120:41
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by jakubpawlowicz** [comment]
Again, it'd be great to have a reproducible test case, like a CSS snippet causing it.

**Comment by jakubpawlowicz** [comment]
Depends on #290 - aggressive merging should be out in 4.0.

**Comment by zodman** [comment]
@jakubpawlowicz  i had a problem can you adviceme how to find the css that causing it ?  a try with a lot printing values but no found the snippet

**Comment by jakubpawlowicz** [comment]
@zodman I'd start with printing `properties` first at https://github.com/jakubpawlowicz/clean-css/blob/3.4/lib/properties/optimizer.js#L133 and that should give you a clue what to look for.

Btw, you can also ditch aggressive merging altogether (`--skip-aggressive-merging` / `aggressiveMerging: false`) as it'll be gone in 4.0.

**Comment by zodman** [comment]
for some reason my gulpfile are minify a js  file ...

stupid code!! long bug closed!

**Comment by jakubpawlowicz** [comment]
no worries 👍 glad you sorted it out
