### ISSUE TITLE
Error "version" is a required argument

### ISSUE THREAD

**Issue by creeperyang** [jakubpawlowicz/clean-css#819]
`node@6.2.1` and `clean-css@@3.4.18`

**Code**

```js
new CleanCSS({
    target: targetUrl,
    sourceMap: true
}).minify({
    '/path1': {
        styles: 'xxxxx',
        sourceMap: 'yyyyy'
    }
}, (error, minified) => {})
```

**Error message**

```bash
Error: "version" is a required argument.
    at Object.getArg (/xx/node_modules/source-map/lib/source-map/util.js:28:13)
    at SourceMapConsumer.BasicSourceMapConsumer (/xx/node_modules/source-map/lib/source-map/source-map-consumer.js:292:24)
    at new SourceMapConsumer (/xx/node_modules/source-map/lib/source-map/source-map-consumer.js:26:9)
    at InputSourceMapStore.trackLoaded (/xx/node_modules/clean-css/lib/utils/input-source-map-tracker.js:252:11)
    at fromHash (/xx/node_modules/clean-css/lib/utils/source-reader.js:88:47)
    at SourceReader.toString (/xx/node_modules/clean-css/lib/utils/source-reader.js:29:10)
    at CleanCSS.minify (/xx/node_modules/clean-css/lib/clean.js:111:31)
    at Promise.all.then.results (/xx/core-plugins.js:134:20)
```

**Comment by jakubpawlowicz** [comment]
@creeperyang does the input source map have a `version` field as source map consumer expects it, see: https://github.com/mozilla/source-map/blob/6008ad4ff77c403d68b22c69a4175ed40834f61a/lib/source-map-consumer.js#L288 and throws an error otherwise.

**Comment by creeperyang** [comment]
Yeah, you're right. The `version` field is required. I manually added `version: 3` and it works.

However I don't know why the source map created by `node-sass` miss this field.
