### ISSUE TITLE
TypeError: Path must be a string. Received undefined on node 6.9.1

### ISSUE THREAD

**Issue by skmvasu** [jakubpawlowicz/clean-css#835]
I'm getting a `TypeError: Path must be a string. Received undefined` on node v6.9.1

I saw issue #774 and upgraded my `clean-css` to `3.4.21`, but I'm still getting the same error. 

<img width="512" alt="screen shot 2016-11-28 at 12 07 49 pm" src="https://cloud.githubusercontent.com/assets/567228/20658576/f38e884e-b563-11e6-8254-f6f27f45234c.png">

I also updated my `less-plugin-clean-css` to `1.5.1`

Here is the full stacktrace

```
Running "less:prod" (less) task
>> TypeError: Path must be a string. Received undefined
>>   at assertPath (path.js:7:11)
>>   at Object.dirname (path.js:1324:5)
>>   at new CleanCSS (/Users/skmvasu/repo/recruiterbox/recruiterbox/static/grunt/node_modules/less-plugin-clean-css/node_modules/clean-css/lib/clean.js:55:130)
>>   at Object.process (/Users/skmvasu/repo/recruiterbox/recruiterbox/static/grunt/node_modules/less-plugin-clean-css/lib/clean-css-processor.js:40:26)
>>   at ParseTree.toCSS (/Users/skmvasu/repo/recruiterbox/node_modules/less/lib/less/parse-tree.js:44:48)
>>   at /Users/skmvasu/repo/recruiterbox/node_modules/less/lib/less/render.js:31:40
>>   at /Users/skmvasu/repo/recruiterbox/node_modules/less/lib/less/parse.js:63:17
>>   at Object.finish [as _finish] (/Users/skmvasu/repo/recruiterbox/node_modules/less/lib/less/parser/parser.js:183:28)
>>   at Object._onSequencerEmpty (/Users/skmvasu/repo/recruiterbox/node_modules/less/lib/less/visitors/import-visitor.js:35:14)
>>   at ImportSequencer.tryRun (/Users/skmvasu/repo/recruiterbox/node_modules/less/lib/less/visitors/import-sequencer.js:50:14)
>>   at /Users/skmvasu/repo/recruiterbox/node_modules/less/lib/less/visitors/import-sequencer.js:19:25
>>   at fileParsedFunc (/Users/skmvasu/repo/recruiterbox/node_modules/less/lib/less/import-manager.js:50:17)
>>   at /Users/skmvasu/repo/recruiterbox/node_modules/less/lib/less/import-manager.js:113:21
>>   at finish (/Users/skmvasu/repo/recruiterbox/node_modules/less/lib/less/parser/parser.js:183:28)
>>   at Object.parse (/Users/skmvasu/repo/recruiterbox/node_modules/less/lib/less/parser/parser.js:191:24)
>>   at loadFileCallback (/Users/skmvasu/repo/recruiterbox/node_modules/less/lib/less/import-manager.js:112:64)
Warning: Error compiling ../../../client-src/less/app.less Use --force to continue.
```

Am I missing something here?

**Comment by jakubpawlowicz** [comment]
Hi @skmvasu!

Although stacktrace points to line 55 I believe it's line #63 as it's the only place which uses `dirname` method: https://github.com/jakubpawlowicz/clean-css/blob/3.4/lib/clean.js#L63

Can you check what's the `target` param the `less-plugin-clean-css` passes into clean-css?

Jakub

**Comment by jakubpawlowicz** [comment]
clean-css 4 gets rid of this piece of code, so please recheck or provide more details for version 3.x.

Closing this issue due to inactivity.
