### ISSUE TITLE
Breaks on path.isAbsolute error after upgrading to 4.0.5

### ISSUE THREAD

**Issue by blissdev** [jakubpawlowicz/clean-css#888]
Environment: Linux
Version: 4.0.5

Command:
```
./node_modules/bin/cleancss -o static/css/all.min.css static/css/all.css
```

Output:
```
./node_modules/clean-css/lib/reader/read-sources.js:97
  absoluteUri = path.isAbsolute(uri) ?
                     ^
TypeError: Object #<Object> has no method 'isAbsolute'
    at normalizeUri (./node_modules/clean-css/lib/reader/read-sources.js:97:22)
    at ./node_modules/clean-css/lib/reader/read-sources.js:56:25
    at Array.reduce (native)
    at fromArray (./node_modules/clean-css/lib/reader/read-sources.js:55:30)
    at doReadSources (/home/jenkins/workspace/development-deploy/node_modules/clean-css/lib/reader/read-sources.js:40:12)
    at readSources (./node_modules/clean-css/lib/reader/read-sources.js:25:10)
    at ./node_modules/clean-css/lib/clean.js:97:12
    at process._tickCallback (node.js:458:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
```

This same command was running successfully at least as late as 4.0.0.

**Comment by blissdev** [comment]
Realized that this server is running an old version of Node which I think is causing this issue. (0.10.x)

**Comment by jakubpawlowicz** [comment]
Yup, `path.isAbsolute` was added in 0.11.2.
