### ISSUE TITLE
TypeError: Object #<Object> has no method 'isAbsolute'

### ISSUE THREAD

**Issue by JonHannah** [jakubpawlowicz/clean-css#896]
I just ran into the error identified in [this SO post](http://stackoverflow.com/questions/42248488/gulp-minify-css-task-fails). Headline details below; happy to provide more code samples if helpful.

* What's your input CSS and expected output?
My CSS is generated in a gulp task
```// Compile Sass files, minify and add .min suffix
gulp.task('styles', function() {
  return gulp.src('frontend/src/sass/**/*.scss')
    // Compile SASS
    .pipe(sass().on('error', sass.logError))
    // Autoprefixer to maximise browser compatibility while writing pure css
    .pipe(autoprefixer())
    // Minify CSS
    .pipe(cleanCSS())
    // Rename CSS (adds .min suffix)
    .pipe(rename({
        suffix: '.min'
    }))
    // Output production CSS Files
    .pipe(gulp.dest('frontend/static/css'));
});
```
* Do you use clean-css directly or through any of the plugins?
gulp-clean-css@3.0.2
* What options do you pass to clean-css / the plugin?
None
* What version of clean-css do you use?
Working @4.0.5, breaks @4.0.7
* What operating system do you use?
Ubuntu 12.04

Below is the traceback from CircleCI:

> nightly@0.0.1 postinstall /home/ubuntu/Nightly
> gulp process

[13:27:48] Using gulpfile ~/Nightly/gulpfile.js
[13:27:48] Starting 'styles'...
[13:27:48] Starting 'scripts'...
[13:27:51] Finished 'scripts' after 2.91 s

/home/ubuntu/Nightly/node_modules/gulp-clean-css/node_modules/clean-css/lib/reader/rewrite-url.js:45
  return path.isAbsolute(uri);
              ^
TypeError: Object #<Object> has no method 'isAbsolute'
    at isAbsolute (/home/ubuntu/Nightly/node_modules/gulp-clean-css/node_modules/clean-css/lib/reader/rewrite-url.js:45:15)
    at rebase (/home/ubuntu/Nightly/node_modules/gulp-clean-css/node_modules/clean-css/lib/reader/rewrite-url.js:23:7)
    at rewriteUrl (/home/ubuntu/Nightly/node_modules/gulp-clean-css/node_modules/clean-css/lib/reader/rewrite-url.js:115:26)
    at rebaseAtRule (/home/ubuntu/Nightly/node_modules/gulp-clean-css/node_modules/clean-css/lib/reader/rebase.js:68:16)
    at rebaseEverything (/home/ubuntu/Nightly/node_modules/gulp-clean-css/node_modules/clean-css/lib/reader/rebase.js:25:9)
    at rebase (/home/ubuntu/Nightly/node_modules/gulp-clean-css/node_modules/clean-css/lib/reader/rebase.js:12:5)
    at fromStyles (/home/ubuntu/Nightly/node_modules/gulp-clean-css/node_modules/clean-css/lib/reader/read-sources.js:140:12)
    at fromString (/home/ubuntu/Nightly/node_modules/gulp-clean-css/node_modules/clean-css/lib/reader/read-sources.js:51:10)
    at doReadSources (/home/ubuntu/Nightly/node_modules/gulp-clean-css/node_modules/clean-css/lib/reader/read-sources.js:36:12)
    at readSources (/home/ubuntu/Nightly/node_modules/gulp-clean-css/node_modules/clean-css/lib/reader/read-sources.js:25:10)

**Comment by jakubpawlowicz** [comment]
See https://github.com/jakubpawlowicz/clean-css/issues/888

Note this is not a regression error - Node.js 4+ is required since clean-css 4.0.0.

**Comment by JonHannah** [comment]
@jakubpawlowicz thanks for the quick response. This is using Node v5.5.0 both locally and on the server and was quite happy @4.0.5. Is it possible anything else changed?

**Comment by JonHannah** [comment]
Then again, looking at the diff 4.0.5 > 4.0.7 there doesn't seem to be ...

**Comment by jakubpawlowicz** [comment]
Hmmm, that's interesting. The error is raised in that particular line: https://github.com/jakubpawlowicz/clean-css/blob/master/lib/reader/rewrite-url.js#L45, which means `path` is somehow to blame. 

Could you spin `node` on the server and check if the following code runs fine there?

```js
var path = require('path');
path.isAbsolute('/usr');
```

**Comment by JonHannah** [comment]
Yep - seems to run just fine ...

```
(venv-3.5.0) ubuntu@box703: $ node -v
v5.5.0
(venv-3.5.0) ubuntu@box703: $ node
> var path = require('path');
undefined
> path
{ resolve: [Function],
  normalize: [Function],
  isAbsolute: [Function],
  join: [Function],
  relative: [Function],
  _makeLong: [Function],
  dirname: [Function],
  basename: [Function],
  extname: [Function],
  format: [Function],
  parse: [Function],
  sep: '/',
  delimiter: ':',
  posix: [Circular],
  win32:
   { resolve: [Function],
     normalize: [Function],
     isAbsolute: [Function],
     join: [Function],
     relative: [Function],
     _makeLong: [Function],
     dirname: [Function],
     basename: [Function],
     extname: [Function],
     format: [Function],
     parse: [Function],
     sep: '\\',
     delimiter: ';' } }
> path.isAbsolute('/usr');
true
```

**Comment by jakubpawlowicz** [comment]
This is baffling, as I've just run tests on Node.js v5.5.0 and it's all green: https://travis-ci.org/jakubpawlowicz/clean-css/builds/202594790

Any chance your build uses an older version of node?

**Comment by JonHannah** [comment]
I'm now also baffled. Re-running the build with clean-css@4.0.7 it now works ...

I suggest we leave it there for now, and pick back up if it resurfaces. I'll update my SO answer

**Comment by jakubpawlowicz** [comment]
I'm glad it works 👍
